### ISSUE TITLE
Do we seriously need to support iojs?

### ISSUE THREAD

**Issue by wayne-o** [waterlock/waterlock#96]
Just that the PRs I tried to merge failed on iojs builds because bcrypt only supports stable Node releases.

Can this be helped? 

I know there is a PR to change the bcrypt dep to a JS only version but I have read bad things about this.

Can anyone help?

**Comment by listepo** [comment]
The latest version of bcrypt supports all major versions iojs https://github.com/ncb000gt/node.bcrypt.js/blob/master/.travis.yml
```yaml
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
```
